### ISSUE TITLE
Invaild arg when creating an event..

### ISSUE THREAD

**Issue by antlusher** [michielgerritsen/laravel-nova-email-on-event#1]
Hello Michiel, thank you for sharing your code. I seem to be getting the following. I've followed your steps, but am I missing something?

All the best, Ant

![Screen Shot 2019-09-13 at 11 18 28](https://user-images.githubusercontent.com/2495026/64855651-4794bd00-d618-11e9-863c-a2cb16378c8a.png)

**Comment by michielgerritsen** [comment]
Hi Ant,

That error is a bit vague 😄When do you get it? Is it when executing a specific action? Could you open the developer tools to check if one of the ajax request has a more descriptive error in it?

**Comment by antlusher** [comment]
Agh, sorry. I'll investigate tomorrow.

**Comment by antlusher** [comment]
Sorry, first time for me posting issues...

So we have the stack trace below...

vendor/michielgerritsen/laravel-nova-email-on-event/src/Service/Files/EventFinder.php45
    private $files = [];
 
    public function __construct(
        ClassNameFinder $classNameFinder
    ) {
        $this->classNameFinder = $classNameFinder;
    }
 
    public function find()
    {
        foreach (app_path('Events') as $path) { // THIS FOR EACH
            $this->findEventsInPath($path);
        }
 
        return $this->files;
    }

And the endpoint:
nova/resources/email-events-resources/new?viaResource=&viaResourceId=&viaRelationship=
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

This error happens on "Create email event"

Maybe we could add a bit of error handling? I'm not sure...

**Comment by antlusher** [comment]
Agh, I know, I have to create the events? I understood that common events already exists? Maybe do something like: no events found, please follow these examples? And kill the loop...

**Comment by michielgerritsen** [comment]
Hi @antlusher,

Thanks for the extra details. I was able to reproduce this problem and just tagged a new release to fix this. I'm not sure how i missed this before.

It is correct that this extension only supports custom created events and not the default system events. I have created this as a MVP, but it's possible to add them. Do you have any events you want to have supported?
