### ISSUE TITLE
send email to multiple users

### ISSUE THREAD

**Issue by kenkaigu** [michielgerritsen/laravel-nova-email-on-event#2]
is it possible to add a feature where you send an event to multiple users?

**Comment by michielgerritsen** [comment]
Currently that's not possible, but i'm going to look if i can add it. Stay tuned.

**Comment by kenkaigu** [comment]
I will really appreciate that. This is a great package. Thank you

**Comment by michielgerritsen** [comment]
Hi @kenkaigu,

The last few weeks i was limited in my time, but i just openend a PR that implements this request. You can check if #3 does this for you.

**Comment by michielgerritsen** [comment]
Hi @kenkaigu,

A moment ago i released version 0.3.0 with these changes.
